MebelWeb/MebelWeb/Models/Products.cs
using MebelWeb.Models;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations.Schema;

namespace MebelWeb.Models
{
    public class Products
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public double Price { get; set; }
        public int CategoryId { get; set; }
        [ForeignKey("CategoryId")]
        [ValidateNever]
        public Category Category { get; set; }
        public List<Orders>Orders { get; set; }
       

    }
}

MebelWeb/MebelWeb/Areas/Admin/Controllers/ProductsController.cs
using MebelWeb.DAL;
using MebelWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;


namespace DMAWebProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductsController : Controller
    {
        private readonly AppDbContext appDbContext;

        public ProductsController(AppDbContext _appDbContext)
        {
            appDbContext = _appDbContext;
        }
        public IActionResult Index()

        {
            
            return View(appDbContext.Products.Include(x => x.Category).ToList());
        }

        public IActionResult Create()
        {
            ViewBag.Category = appDbContext.Categories.ToList();

            return View();
        }

        [HttpPost]
        public IActionResult Create(Products model)
        {

            if (!ModelState.IsValid)
            {
                ViewBag.Category = appDbContext.Categories.ToList();
                return View(model);
            }

            appDbContext.Products.Add(model);
            appDbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            ViewBag.Category = appDbContext.Categories.ToList();
            var model = appDbContext.Products.FirstOrDefault(x => x.Id == id);

            return View(model);
        }
    }
}

MebelWeb/MebelWeb/Areas/Admin/Controllers/SliderController.cs
using MebelWeb.Controllers;
using MebelWeb.DAL;
using MebelWeb.Extencion;
using MebelWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace MebelWeb.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SliderController : Controller
    {
        private readonly AppDbContext appDbContext;
        private readonly IWebHostEnvironment _env;


        public SliderController(AppDbContext _appDbContext, IWebHostEnvironment env)
        {
            appDbContext = _appDbContext;
            _env = env;
        }
        public IActionResult Index()
        {
            return View(appDbContext.Sliders.ToList());
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Slider slider)
        {
            if (!ModelState.IsValid)

            {
                return View(slider);
            }
            if (!slider.ImgFile.IsImage())
            {
                ModelState.AddModelError("Photo", "Image type is not valid");
            }
            slider.ImgUrl = await slider.ImgFile.SaveFileAsync(_env.WebRootPath, "Images");
            appDbContext.Sliders.Add(slider);
            appDbContext.SaveChanges();

            return RedirectToAction("Index");
        }

        public JsonResult Delete(int id)
        {
            if (id == 0)
            {
                return Json(new
                {
                    status = 400
                });
            }

            var slider = appDbContext.Sliders.Find(id); //axtarib tapiram
            if (slider != null)
            {
                slider.IsCheck = false; ;
                appDbContext.SaveChanges();
            }

            return Json(new
            {
                status = 200
            });

        }

        [HttpGet]
        public JsonResult Edit(int id)
        {
            if (id == 0)
            {
                return Json(new
                {
                    status = 400
                });
            }
            var model = appDbContext.Sliders.FirstOrDefault(x => x.Id == id);
            if (model == null)
            {
                return Json(new
                {
                    status = 400
                });
            }
            return Json(model);
        }

        [HttpPost]
        public async Task<IActionResult> EditAsync(Slider slider)
        {

            if (!ModelState.IsValid)
            {
                return View(slider);

            }

            string filename = await slider.ImgFile.SaveFileAsync(_env.WebRootPath, "Images");
            slider.ImgUrl = filename;
            appDbContext.Sliders.Update(slider);
            appDbContext.SaveChanges();

            return RedirectToAction("Index");

        }
    }
}

MebelWeb/MebelWeb/Areas/Admin/Views/Products/Create.cshtml
@model Products

<div class="page-content">
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                    <h4 class="mb-sm-0 font-size-18">Jobs Grid</h4>

                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="javascript: void(0);">Jobs</a></li>
                            <li class="breadcrumb-item active">Jobs Grid</li>
                        </ol>
                    </div>

                </div>
            </div>
        </div>
        <!-- end page title -->


        <div class="row">
            <div class="col-lg-12">
                <div class="card job-filter">
                    <div class="card-body p-3">
                        <form class="row" method="post" enctype="multipart/form-data" asp-area="admin" asp-controller="products" asp-action="create">
                            @Html.AntiForgeryToken()
                            <div class="col-md-3">
                                <label>
                                    Title
                                </label>
                                <input asp-for="Title" type="text" class="form-control" />
                                <span asp-validation-for="Title" class="text-danger"></span>

                            </div>
                           
                            <div class="col-md-3">
                                <label>
                                    Description
                                </label>
                                <input asp-for="Description" type="text" class="form-control" />
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                            <div class="col-md-3">
                                <label>
                                 Price
                                </label>
                                <input asp-for="Price" type="text" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>

                            </div>
                            <div class="col-md-3">
                                <label>
                                   Category
                                </label>
                                <select class="form-select" asp-for="CategoryId">
                                    @foreach(var item in ViewBag.Category)
                                    {
                                        <option value="@item.Id">@item.Name</option>
                                    } 
                                    
                                </select>
                            </div>
                            <div class="col-md-3">
                                <button type="submit" class="btn btn-danger mt-3 btn-block"> Add database</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><!-- End Page-content -->

MebelWeb/MebelWeb/Areas/Admin/Views/Products/Edit.cshtml
@model Products

<div class="page-content">
    <div class="container-fluid">

        <!-- start page title -->
        <div class="row">
            <div class="col-12">
                <div class="page-title-box d-sm-flex align-items-center justify-content-between">
                    <h4 class="mb-sm-0 font-size-18">Jobs Grid</h4>

                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="javascript: void(0);">Jobs</a></li>
                            <li class="breadcrumb-item active">Jobs Grid</li>
                        </ol>
                    </div>

                </div>
            </div>
        </div>
        <!-- end page title -->


        <div class="row">
            <div class="col-lg-12">
                <div class="card job-filter">
                    <div class="card-body p-3">
                        <form class="row" method="post" enctype="multipart/form-data" asp-area="admin" asp-controller="slider" asp-action="create">
                            @Html.AntiForgeryToken()
                            <div class="col-md-3">
                                <label>
                                    Title
                                </label>
                                <input asp-for="Title" type="text" class="form-control" />
                                <span asp-validation-for="Title" class="text-danger"></span>

                            </div>

                            <div class="col-md-3">
                                <label>
                                    Description
                                </label>
                                <input asp-for="Description" type="text" class="form-control" />
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                            <div class="col-md-3">
                                <label>
                                    Price
                                </label>
                                <input asp-for="Price" type="text" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>

                            </div>
                            <div class="col-md-3">
                                <label>
                                    Category
                                </label>
                                <select class="form-select" asp-for="CategoryId">
                                    @foreach (var item in ViewBag.Category)
                                    {
                                        <option value="@item.Id">@item.Name</option>
                                    }

                                </select>
                            </div>
                            <div class="col-md-3">
                                <button type="submit" class="btn btn-danger mt-3 btn-block"> Add database</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><!-- End Page-content -->

MebelWeb/MebelWeb/Areas/Admin/Views/Products/Index.cshtml
@model List<Products>


<div class="page-content">
    <div class="container-fluid">

        <a class="btn btn-success" asp-area="Admin" asp-controller="Products" asp-action="Create">Create new Products</a>
        <div class="row">
            <div class="col-lg-12">
                <div class="card job-filter">
                    <div class="card-body p-3">
                        <table class="table">
                            <thead>
                                <tr>
                                   
                                    <th scope="col">Title</th>
                                    <th scope="col">Description</th>
                                    <th scope="col">Price</th>
                                    <th scope="col">Category</th>
                                    <th scope="col">Operation</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @item.Title
                                        </td>
                                        <td>
                                            @item.Description
                                        </td>
                                        <td>
                                            @item.Price
                                        </td>
                                        <td>
                                            @item.Category.Name
                                        </td>
                                        <td>
                                            <a class="deleteBtn btn btn-danger" asp-area="Admin" asp-controller="Slider" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                                            <button data-id="@item.Id" type="button" class="editBtn btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModalEdit">
                                                Edit
                                            </button>

                                        </td>
                                    </tr>
                                }

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>


    </div>
</div>